export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const BUS_LIST = 'BUS_LIST'
export const BUS_INFO = 'BUS_INFO'
export const BUS_DETAILS_LIST = 'BUS_DETAILS_LIST'
export const BUS_STATUS = 'BUS_STATUS'
export const BUS_CLEAR = 'BUS_CLEAR'
export const BUS_TAG_LIST = 'BUS_TAG_LIST'
export const BUS_TAG_CLEAR = 'BUS_TAG_CLEAR'
export const BUS_TAG_CHANGE = 'BUS_TAG_CHANGE'
export const BUS_KEYWORD = 'BUS_KEYWORD'

export const MEAL_LIST = 'MEAL_LIST'
export const MEAL_STATUS = 'MEAL_STATUS'
export const MEAL_CLEAR = 'MEAL_CLEAR'
export const MEAL_TAG_LIST = 'MEAL_TAG_LIST'
export const MEAL_TAG_CLEAR = 'MEAL_TAG_CLEAR'
export const MEAL_TAG_CHANGE = 'MEAL_TAG_CHANGE'
